import Hero from "./components/hero";
import Navbar from "./components/Navbar";
import OurSpeciality from "./components/OurSpeciality";
import Reviews from "./components/Reviews";
export default function Home() {
  return (
   
   <>
<Navbar/>
   <Hero/>
   <OurSpeciality/>
   <Reviews/>
   {/* <Footer/> */}
   <div className="h-[1000px] w-full bg-[]"></div>
  
   </>
  );
}
export const metadata = {
  title: "The Roasted Garden",
  description: "Generated by create next app",
};
