import Hero from "./components/HomePage/hero";
import Navbar from "./components/Navbar";
import OurSpeciality from "./components/HomePage/OurSpeciality";
import Reviews from "./components/Reviews";
import About from "./components/HomePage/about";
export default function Home() {
  return (

    <>
      
      <Hero />
      <OurSpeciality />
      <Reviews />
      <About />
      {/* <Footer/> */}


    </>
  );
}
export const metadata = {
  title: "The Roasted Garden",
  description: "Generated by create next app",
};
